apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-rest
  name: spring-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-rest
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-rest 
    spec:
      containers:
      - image: gonzaloacosta/devops-spring-rest:0.0.2-SNAPSHOT
        name: spring-rest 
        ports:
        - containerPort: 8080
